### PR TITLE
[MadNLPHSL] Use HSL.jl

### PR DESCRIPTION
**Pull request by amontoison**
I started to remove the Julia wrappers but for some C structures (ma97_control, ma77_info, etc...) we should switch to the one defined in `HSL.jl`.

Note that with the dummy `HSL_jll.jl` available for everyone, `MadNLPHSL` could be merged in `MadNLP` because we can check if we can use the HSL solvers with `LIBHSL_isfunctional()`

### CODE REVIEW

**Comment by sshin23** [comment]
Thanks @amontoison for working on this. I was wondering if it would be possible for HSL.jl to implement some initialization of `HSL.ma**_info` and `HSL.ma**_control` using keyword arguments so that `HSL.ma**_info` and `HSL.ma**_control` can be created without having to specify all the values. I think this can further specify interfacing with HSL solvers

**Comment by amontoison** [comment]
Hi @sshin23,

Yes, we can do that. Can you open an issue or a small PR in HSL.jl?

**Comment by amontoison** [comment]
@sshin23 
Do you know that you can easily create a a `ma**_control` with `new()` and after call the routine `default_control`?

**Comment by sshin23** [comment]
An issue opened in HSL.jl [@amontoison Ah, you mean ](https://github.com/JuliaSmoothOptimizers/HSL.jl/issues/202)

**Comment by sshin23** [comment]
@amontoison Ah, you mean [incomplete initialization](https://docs.julialang.org/en/v1/manual/constructors/#Incomplete-Initialization)? I think that should work as well

**Comment by amontoison** [comment]
@sshin23 I did a new release of `HSL.jl` and updated `MadNLPHSL.jl`.

**Review by sshin23 — APPROVED** [review]
Thanks @amontoison for working on this!

**Pull request merged**
