### PR TITLE
Port MadNLP to MOI 0.10 and JuMP 0.22

### PR DESCRIPTION
**Pull request by frapac**
- MadNLPGraph is not yet compatible with JuMP 0.22
- MINLPTests's tests have been commented out: they are passing, but MINLPTests requires JuMP 0.22 too

### CODE REVIEW

**Comment by frapac** [comment]
For MINLPTests: https://github.com/jump-dev/MINLPTests.jl/pull/34

**Comment by frapac** [comment]
`MadNLPGraph` is now working with JuMP 0.22 and Plasmo 0.4.3. However, I am not sure to understand where does the current error comes from in the tests ...

**Comment by blegat** [comment]
Just a notice that we will release JuMP v1.0 in a few days

**Comment by frapac** [comment]
Thanks for the reminder! This PR is ready to merge, we can make a new release for MadNLP with MOI 1.0 in the next few days.

**Comment by frapac** [comment]
Finally, tests are passing!

**Pull request merged**
