### PR TITLE
[LinearSolvers] Add support for LDL factorization in CHOLMOD

### PR DESCRIPTION
**Pull request by frapac**
cc @amontoison

### CODE REVIEW

**Review by sshin23 — APPROVED** [review]
LGTM! Have you observed any difference in performance?

**Review by amontoison — APPROVED** [review]

**Comment by amontoison** [comment]
I think that they they did a major upgrade of SuiteSparse between Julia 1.10 (SuiteSparse 7.0.4) and Julia 1.9 (SuiteSparse 5.1.0).
Do we want to support both version of SuiteSparse or just bump the compat entry of Julia?

Off-topic: They added a function to provide the version number of CHOLMOD: https://github.com/JuliaSparse/SparseArrays.jl/commit/f890a1e13fc04c295cec48a9b08b76c6e1a7039a#diff-381fd98354d4dbfb825a400525529893f96061bad172b21f755066851fb1f49cR5

**Comment by frapac** [comment]
> LGTM! Have you observed any difference in performance?

Currently running the benchmark on OPF instances ! Cholmod-LDL was slower than LDLFactorizations in my previous tests, but I was not using the correct inertia in MadNLP. 

> Do we want to support both version of SuiteSparse or just bump the compat entry of Julia?

Good point Alexis. I would suggest we support CHOLMOD-LDL only on Julia 1.10 then. What do you think would be best?

**Comment by amontoison** [comment]
Yes, I think that it's best to simply add a check for `VERSION ≥ v"1.10"` and return an error that explicitly states that this linear solver is only supported with Julia 1.10.

**Comment by sshin23** [comment]
Agreed with @amontoison's suggestion

**Review by sshin23 — APPROVED** [review]

**Review by amontoison — APPROVED** [review]

**Pull request merged**
